### ISSUE TITLE
Generate Release?

### ISSUE THREAD

**Issue by rluria14** [aws/sagemaker-pytorch-serving-container#15]
Could you possibly generate a release for the latest version? Trying to get this added to conda-forge and need a release.

@jpeddicord @mvsusp @laurenyu @nskool @akartsky @ChuyangDeng 

Thanks!

**Comment by agcopenhaver** [comment]
Bump

**Comment by rluria14** [comment]
Bump #2

**Comment by laurenyu** [comment]
sorry for the delayed response. what is your use case for wanting this released as a Python library? (we don't have PyPI releases for any of the sagemaker-*-container repositories.)

**Comment by rluria14** [comment]
@laurenyu thanks for the response. i would like to add it to conda-forge and need a tarball in order to proceed. could you generate a release on the github page?

**Comment by rluria14** [comment]
@laurenyu please let me know when you get a chance. thanks!

**Comment by nadiaya** [comment]
We have added two github releases: https://github.com/aws/sagemaker-pytorch-serving-container/releases

And we have released it to pypi:
https://pypi.org/project/sagemaker-pytorch-inference/
