### ISSUE TITLE
docker build should aimed to cpu

### ISSUE THREAD

**Issue by lielran** [aws/sagemaker-pytorch-serving-container#5]
https://github.com/aws/sagemaker-pytorch-serving-container/blob/79fa1f87e44f5f4f1420aa3a64514e352c7f3bf1/buildspec.yml#L57

**Comment by laurenyu** [comment]
thanks for bringing this to our attention! I've created a PR to fix it: https://github.com/aws/sagemaker-pytorch-serving-container/pull/11.
